sudo: required
language: node_js
node_js:
#  - stable
  - 10
  - 9
  - 8
#  - 6
#  - 4
#  - 0.12
#  - 0.11

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json
  - npm install sqlite3 --build-from-source

env:
  - CONNECTIONS=mysql
  - CONNECTIONS=mariadb
  - CONNECTIONS=sqlite
  - CONNECTIONS=postgres
  - CONNECTIONS=sqljs
  # - CONNECTIONS=mssql
  # - CONNECTIONS=oracle
  - CONNECTIONS=mongodb

script:
  - npm run lint
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
