sudo: required
language: node_js
node_js:
  - 11
  - 10
  - 8
cache: npm

services:
  - docker

before_script:
  - sudo service mysql stop & sudo service postgresql stop & cp ormconfig.travis.json ormconfig.json
  - docker-compose pull & npm install sqlite3 --build-from-source & npm run lint & npm run compile && docker-compose up -d

after_success:
  - bash <(curl -s https://codecov.io/bash)
