sudo: required
language: node_js
cache: npm
node_js:
#  - stable
  - 10
  - 9
  - 8
#  - 6
#  - 4
#  - 0.12
#  - 0.11

services:
  - docker

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      before_script:
        - sudo service mysql stop
        - sudo service postgresql stop
        - docker-compose up -d $CONNECTIONS || true
        - cp ormconfig.travis.json ormconfig.json
      env:
        - CONNECTIONS=mysql
        - CONNECTIONS=mariadb
        - CONNECTIONS=sqlite
        - CONNECTIONS=postgres
        - CONNECTIONS=sqljs
        # - CONNECTIONS=mssql
        # - CONNECTIONS=oracle
        - CONNECTIONS=mongodb
      script:
        - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
