sudo: required
language: node_js
node_js:
#  - stable
  - 10
  - 9
  - 8
#  - 6
#  - 4
#  - 0.12
#  - 0.11
cache: 
  directories:
    - ~/docker-images
  npm: true

env:
  - CONNECTIONS=mysql
  - CONNECTIONS=mysql
  - CONNECTIONS=mysql
  - CONNECTIONS=mariadb
  - CONNECTIONS=mariadb
  - CONNECTIONS=mariadb
  - CONNECTIONS=postgres
  - CONNECTIONS=postgres
  - CONNECTIONS=postgres

services:
  - docker

install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - mkdir -p ~/docker-images
  - if [ -e ~/docker-images/typeorm-$NODE_VERSION.tgz ]; then
      docker load -i ~/docker-images/typeorm-$NODE_VERSION.tgz;
    fi
  - cp ormconfig.travis.json ormconfig.json
  - docker-compose up -d $CONNECTIONS || true
  - docker build --build-arg NODE_VERSION=$NODE_VERSION --cache-from=typeorm-$NODE_VERSION -t typeorm-$NODE_VERSION .
  - docker save typeorm-$NODE_VERSION | gzip > ~/docker-images/typeorm-$NODE_VERSION.tgz
  - docker export 

script:	
  - docker run --rm -e "CONNECTIONS=$CONNECTIONS" --network="host" typeorm-$NODE_VERSION npm t

after_success:
  - bash <(curl -s https://codecov.io/bash)
