sudo: required
language: node_js
cache: npm
node_js:
#  - stable
  - 10
  - 9
  - 8
#  - 6
#  - 4
#  - 0.12
#  - 0.11

services:
  - docker

env:
  - CONNECTIONS=mysql
  - CONNECTIONS=mariadb
  - CONNECTIONS=sqlite
  - CONNECTIONS=postgres
  - CONNECTIONS=sqljs
  # - CONNECTIONS=mssql
  # - CONNECTIONS=oracle
  - CONNECTIONS=mongodb

stages:
  - lint
  - build
  - test

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d $CONNECTIONS || true
  - cp ormconfig.travis.json ormconfig.json

script:
  - npm run test-only

jobs:
  include:
    - stage: lint
      env:
        - CONNECTIONS=none
      node_js:
        - 10
      script:
        - npm run lint
    - stage: lint
      env:
        - CONNECTIONS=none
      node_js:
        - 9
      script:
        - npm run lint
    - stage: lint
      env:
        - CONNECTIONS=none
      node_js:
        - 8
      script:
        - npm run lint
    - stage: build
      env:
        - CONNECTIONS=none
      node_js:
        - 10
      script:
        - npm run build
    - stage: build
      env:
        - CONNECTIONS=none
      node_js:
        - 9
      script:
        - npm run build
    - stage: build
      env:
        - CONNECTIONS=none
      node_js:
        - 8
      script:
        - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
